[tool.black]
# line-length = 100
target-version = ['py36', 'py37', 'py38', 'py39']

[tool.isort]
profile = "black"
multi_line_output = 3

[[tool.mypy.overrides]]
module = [
    'sssom.sssom_datamodel',
    'sssom.cliquesummary'
]
ignore_errors = true
