name: Auto-deployment of Documentation
on:
  push:
    branches: [ master ]
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2
      with:
        fetch-depth: 0

    - name: Set up Python 3.
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 2.1.3

    - name: Install dependencies.
      run: |
        poetry add setuptools@latest
        poetry install --extras docs

    - name: Build documentation.
      run: |
        poetry run mkdocs build --strict

    - name: Deploy documentation.
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        branch: gh-pages
        force: true
        folder: site
        token: ${{ secrets.GH_TOKEN }}
