name: Auto-deployment of Documentation
on:
  push:
    branches: [ master ]
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    
    - name: Set up Python 3.
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies.
      run: |
        pip install -e .[docs]

    - name: Build documentation.
      run: |
        mkdir gh-pages
        touch gh-pages/.nojekyll
        cd docs/
        make clean html
        cp -r _build/html/* ../gh-pages/
    
    - name: Deploy documentation.
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@v4.3.0
      with:
        branch: gh-pages
        force: true
        folder: gh-pages