name: sssom-py QC

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [ "3.10", "3.11", "3.12" ]

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098 # v7.3.1
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      
      - name: Windows specific step.
        if: matrix.os == 'windows-latest'
        run: echo "${HOME}/.local/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Check code quality with flake8
        run: uv run tox -e flake8

      - name: Check static typing with MyPy
        run: uv run tox -e mypy

      - name: Test with pytest and generate coverage file
        run: uv run tox -e py
